apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: fitcycle-server
  labels:
    app: fitcycle
spec:
  selector:
    matchLabels:
      app: fitcycle
      tier: app
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: fitcycle
        tier: app
    spec:
      volumes:
      - name: varlog
        emptyDir: {}
      containers:
      - image: gcr.io/learning-containers-187204/web-server-ml:latest
        name: fitcycle-server
        env:        
        - name: MYSQL_ID
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_SERVER
          value: fitcycle-mysql
        ports:
        - containerPort: 8000
          name: fitcycle-server
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      
