apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
spec:
  rules:
    - host: cluster822114532-973a43c4-a63b-11e8-86a9-06acd08d35a2.bfd7a751-b2f5-43a3-b2b3-0c82d6896aee.vke-user.com
      http:
        paths:
        - backend:
            serviceName: fitcycle-web
            servicePort: 8000
          path: /
        - backend:
            serviceName: fitcycle-api
            servicePort: 5000
          path: /api/v1.0/signups

