apiVersion: v1
kind: Service
metadata:
  name: fitcycle-mysql
  labels:
    app: fitcycle
spec:
  ports:
    - port: 3306
      name: http-fc-db
    - name: metrics
      protocol: TCP
      port: 9273
  selector:
    app: fitcycle
    tier: db
  clusterIP: None
