apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: fitcycle-mysql
  labels:
    app: fitcycle
spec:
  selector:
    matchLabels:
      app: fitcycle
      tier: db
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: fitcycle
        tier: db
      annotations:
        prometheus.io/scrape: "true" 
        prometheus.io/port: "9273"
    spec:
      containers:
      - image: percona:5.6
        name: fc-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: fc-mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: fitcycle-persistent-storage
        - mountPath: /docker-entrypoint-initdb.d
          name: mysql-initdb
        - mountPath: /etc/mysql/conf.d
          name: mysql-cnf-config
      - image: gcr.io/learning-containers-187204/telegraf-prom-output:latest
        name: telegraf
        ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
        - name: metrics
          containerPort: 9273
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy
        - name: INTERVAL
          value: 60s
        - name: METRIC_SOURCE_NAME
          # This can be change to use the Deployment / Statefulset name instead as a simple value
          # The metric source name should not be an ephemeral value
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-mysql-config
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: fitcycle-persistent-storage
        persistentVolumeClaim:
          claimName: fc-mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
      - name: telegraf-mysql-config
        configMap:
          name: telegraf-mysql-config
      - name: mysql-cnf-config
        configMap:
          name: mysql-cnf-config
 
