apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE `prospect`;
    USE `prospect`;
    CREATE TABLE `polls_prospect` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `firstname` varchar(100) NOT NULL,
      `lastname` varchar(100) NOT NULL,
      `email` varchar(100) NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
    INSERT INTO polls_prospect VALUES (1,'bill','north','bill@north.com'),(2,'Bill','Shetti','bill@gmail.com'),(3,'Zoe','Shetti','zoe@gmail.com'),(4,'Emi','Shetti','emi@gmail.com'),(5,'Emiko','Shetti','e@gmail.com'),(6,'Jason','Bourne','jason@supremacy.com'),(7,'Donald','Duck','donald@disney.com'),(8,'Sean','ODell','sean@vmware.com'),(9,'Bahubali','Shetti','bahubali@gmail.com'),(10,'Dan','Illson','illson@vmware.com');

