apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-cnf-config
data:
  debian.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
    ignore-db-dir=lost+found
    #general_log=1
    #general_log_file=/var/log/mysql/query.log
