apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: local-fitcycle
  labels:
    app: fitcycle
spec:
  selector:
    matchLabels:
      app: fitcycle
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fitcycle
        tier: app
    spec:
      volumes:
      - name: "fitcycle-apiserver-data"
        hostPath:
          path: "/var/lib/fitcycle-api-server"
      - name: telegraf-config
        configMap:
          name: telegraf-config
      - name: wavefront-output
        configMap:
          name: wavefront-output 
      containers:
      - image: gcr.io/learning-containers-187204/fitcycle-api:latest
        name: local-fitcycle
        env:        
        - name: MYSQL_ID
          value: "root"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_SERVER
          value: fitcycle-mysql
        ports:
        - containerPort: 5000
          name: local-fitcycle
        volumeMounts:
        - mountPath: "/data"
          name: "fitcycle-apiserver-data"
      - image: telegraf
        name: telegraf
        ports:
        - name: statsd
          containerPort: 8125
          protocol: UDP
        volumeMounts:
        - name: wavefront-output
          mountPath: /etc/telegraf/telegraf.d
