apiVersion: v1
kind: Service
metadata:
  name: api-server
  labels:
    app: fitcycle
spec:
  ports:
    - name: http-fcapi
      protocol: TCP
      port: 5000
      nodePort: 30431
  selector:
    app: fitcycle
    tier: api
  type: NodePort
