apiVersion: v1
kind: Service
metadata:
  name: api-fitcycle
  labels:
    app: fitcycle
spec:
  ports:
    - port: 5000
      name: api-fc
  selector:
    app: fitcycle
    tier: api
  type: NodePort
