apiVersion: v1
kind: Service
metadata:
  name: web-server
  labels:
    app: fitcycle
spec:
  ports:
    - port: 8000
      name: http-fcweb
      nodePort: 30440
  selector:
    app: fitcycle
    tier: web
  type: NodePort
