apiVersion: v1
kind: Service
metadata:
  name: api-fitcycle
  labels:
    app: fitcycle
spec:
  ports:
    - name: http-fc
      protocol: TCP
      port: 5000
      nodePort: 30431
    - name: prom
      protocol: TCP
      port: 9273
  selector:
    app: fitcycle
    tier: api
  type: NodePort
